/*
 * global interactive helpers for the cake shop
 * - toast notifications (Bootstrap 4)
 * - AJAX cart operations with badge updates
 * - simple live-search and counter animations
 * - utilities for parsing flash messages generated by PHP
 */

(function ($) {
    "use strict";

    // ensure a toast container is present
    function ensureToastContainer() {
        if ($('#toast-container').length === 0) {
            $('body').append(
                '<div id="toast-container" aria-live="polite" aria-atomic="true" style="position: fixed; top: 1rem; right: 1rem; z-index: 1060;"></div>'
            );
        }
    }

    // show a toast
    window.showToast = function (message, type) {
        type = type || 'info'; // primary, success, info, warning, danger
        ensureToastContainer();
        var toastId = 'toast-' + Date.now();
        var markup =
            '<div id="' + toastId + '" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="3000">' +
            '  <div class="toast-header bg-' + type + ' text-white">' +
            '    <strong class="mr-auto">' + (type.charAt(0).toUpperCase() + type.slice(1)) + '</strong>' +
            '    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">' +
            '      <span aria-hidden="true">&times;</span>' +
            '    </button>' +
            '  </div>' +
            '  <div class="toast-body">' + message + '</div>' +
            '</div>';
        $('#toast-container').append(markup);
        $('#' + toastId).toast('show');
    };

    // parse flash message from an element #flash if present
    function handleFlash() {
        var $f = $('#flash');
        if ($f.length) {
            var msg = $f.data('message');
            var type = $f.data('type') || 'info';
            if (msg) {
                showToast(msg, type);
            }
            $f.remove();
        }
        // also look for "msg" and "type" query parameters so pages can send messages generically
        var params = new URLSearchParams(window.location.search);
        if (params.has('msg')) {
            var message = params.get('msg');
            var t = params.get('type') || 'info';
            showToast(message, t);
        }
    }

    // cart badge update helper
    function updateCartBadge(cnt) {
        $('.cart-badge, .badge').text(cnt);
    }

    // add item to cart via AJAX
    window.add_cart = function (product_id) {
        $.ajax({
            url: 'fetch_cart.php',
            data: { id: product_id },
            method: 'get',
            cache: false,
            dataType: 'json',
            success: function (cart) {
                updateCartBadge(cart.length);
                window.location.href = 'cart.php?msg=Item%20added%20to%20cart&type=success';
            },
            error: function () {
                showToast('Unable to add to cart', 'danger');
            }
        });
    };

    // remove item from cart via AJAX
    window.remove_cart = function (index) {
        $.ajax({
            url: 'remove_product.php',
            data: { val_i: index, ajax: 1 },
            method: 'get',
            dataType: 'json',
            success: function (cart) {
                // if server returns updated cart array
                updateCartBadge(cart.length);
                showToast('Item removed from cart', 'warning');
                // reload page to update table if necessary
                location.reload();
            },
            error: function () {
                showToast('Unable to remove item', 'danger');
            }
        });
    };

    // animate numbers for statistics
    function animateCounters() {
        $('.stat-number').each(function () {
            var $el = $(this);
            var final = parseInt($el.text(), 10);
            $el.text('0');
            $({ count: 0 }).animate({ count: final }, {
                duration: 1500,
                easing: 'swing',
                step: function () {
                    $el.text(Math.floor(this.count));
                }
            });
        });
    }

    // live search on shop page
    function wireLiveSearch() {
        var $searchInput = $('#searchInput');
        if ($searchInput.length) {
            $searchInput.on('input', function () {
                var term = $(this).val().toLowerCase();
                $('.product-thumbnail').each(function () {
                    var name = $(this).find('.product-title').text().toLowerCase();
                    var isMatch = name.indexOf(term) !== -1;
                    $(this).closest('.col-xl-3').toggle(isMatch);
                });
            });
        }
    }

    // scroll-triggered animations
    function initScrollAnimations() {
        var animatedElements = $('.animate-fade-in-up, .animate-fade-in-left, .animate-fade-in-right, .animate-bounce-in, .animate-slide-in-up');

        function checkScroll() {
            var windowHeight = $(window).height();
            var scrollTop = $(window).scrollTop();

            animatedElements.each(function () {
                var elementTop = $(this).offset().top;
                var elementVisible = elementTop - windowHeight + 100;

                if (scrollTop > elementVisible) {
                    $(this).addClass('animated');
                }
            });
        }

        // Check on load
        checkScroll();

        // Check on scroll
        $(window).on('scroll', checkScroll);
    }

    $(document).ready(function () {
        handleFlash();
        animateCounters();
        wireLiveSearch();
        initScrollAnimations();
    });

})(jQuery);

// Live Message Preview
function updateCakeMessage(msg) {
    document.querySelectorAll('.cake-msg-preview').forEach(el => {
        el.innerText = msg;
    });
}



// Live Message Preview global function
function updateCakeMessage(msg) {
    document.querySelectorAll('.cake-msg-preview').forEach(el => {
        el.innerText = msg;
    });
}

// Wishlist Micro-interaction
$(document).ready(function () {
    $('.wishlist-icon').on('click', function (e) {
        e.preventDefault();
        $(this).toggleClass('active');
        if ($(this).hasClass('active')) {
            $(this).find('i').removeClass('far').addClass('fas');
        } else {
            $(this).find('i').removeClass('fas').addClass('far');
        }
    });

    // Add to cart bounce
    $('.btn-add-cart-bounce').on('click', function () {
        var btn = $(this);
        btn.addClass('btn-bounce-active');
        setTimeout(function () {
            btn.removeClass('btn-bounce-active');
        }, 400);
    });
});

function surpriseMe(btn) {
    if (btn) {
        let oldHTML = btn.innerHTML;
        btn.innerHTML = '<i class="fas fa-spinner fa-spin mr-2"></i> Picking...';
    }
    setTimeout(() => {
        window.location.href = 'shop.php?surprise=1';
    }, 600);
}
